XOOPS/XoopsCore26

htdocs/xoops_lib/smarty/xoops_plugins/resource.admin.php, htdocs/xoops_lib/smarty/xoops_plugins/resource.block.php, htdocs/xoops_lib/smarty/xoops_plugins/resource.module.php
Note: issues still exist for cache filenames
=> Fix for compiled template filename under Windows

htdocs/install/page_dbsettings.php
This fix is for a problem found when investigating #245.
=> Install using incorrect DB in some cases

htdocs/class/xoopseditor/tinymce/tinymce.php, htdocs/class/xoopseditor/tinymce4/tinymce.php, htdocs/kernel/privmessage.php, htdocs/modules/banners/class/form/banner.php, htdocs/modules/monolog/preloads/preload.php, htdocs/modules/page/class/plugin/system.php, htdocs/modules/publisher/blocks/latest_news.php, htdocs/modules/userconfigs/class/plugin/system.php, htdocs/xoops_lib/Xmf/Module/Cache.php, htdocs/xoops_lib/Xoops.php, htdocs/xoops_lib/Xoops/Core/Assets.php, htdocs/xoops_lib/Xoops/Core/Cache/CacheManager.php, htdocs/xoops_lib/Xoops/Core/Psr4ClassLoader.php, htdocs/xoops_lib/Xoops/Form/Form.php, htdocs/xoops_lib/Xoops/Form/GroupCheckbox.php
=> Revert "A few fixes for issues reported by scrutinizer"

htdocs/class/xoopseditor/tinymce/tinymce.php, htdocs/class/xoopseditor/tinymce4/tinymce.php, htdocs/kernel/privmessage.php, htdocs/modules/banners/class/form/banner.php, htdocs/modules/monolog/preloads/preload.php, htdocs/modules/page/class/plugin/system.php, htdocs/modules/publisher/blocks/latest_news.php, htdocs/modules/userconfigs/class/plugin/system.php, htdocs/xoops_lib/Xmf/Module/Cache.php, htdocs/xoops_lib/Xoops.php, htdocs/xoops_lib/Xoops/Core/Assets.php, htdocs/xoops_lib/Xoops/Core/Cache/CacheManager.php, htdocs/xoops_lib/Xoops/Core/Psr4ClassLoader.php, htdocs/xoops_lib/Xoops/Form/Form.php, htdocs/xoops_lib/Xoops/Form/GroupCheckbox.php
=> Revert "Revert "A few fixes for issues reported by scrutinizer""

htdocs/xoops_lib/Xoops/Core/Cache/CacheManager.php
Somehow these didn't follow along like expected? Sorry for the mess.
=> The rest of the fixes from #299

.gitignore, htdocs/install/page_siteinit.php, htdocs/xoops_data/stash/index.html, htdocs/xoops_lib/Xoops/Core/Cache/CacheManager.php
Fix for cache errors during install, add OS adapting configuration
=> Cache fixes

tests/unit/xoopsLib/Xoops/Auth/AdsTest.php, tests/unit/xoopsLib/Xoops/Auth/FactoryTest.php, tests/unit/xoopsLib/Xoops/Auth/LdapTest.php, tests/unit/xoopsLib/Xoops/Auth/ProvisioningTest.php, tests/unit/xoopsLib/Xoops/Core/Cache/CacheManagerTest.php, tests/unit/xoopsLib/Xoops/Core/SecurityTest.php, tests/unit/xoopsLib/XoopsTest.php
Fixing several tests that were broken with recent changes.
=> Fix some broken tests

README.md
=> Tweak button URLs

htdocs/install/include/config.php
=> Remove non-existing paths from "make this writable" list

.scrutinizer.yml
=> Adjust coverage timeout

htdocs/xoops_lib/Xoops/Core/Session/Handler.php
Corrects some very odd behavior caused by updates quietly failing.
=> Fix writes to system_session table

console/Commands/CiBootstrapCommand.php, htdocs/class/XoopsBaseConfig.php, htdocs/xoops_lib/Xoops.php, htdocs/xoops_lib/Xoops/Core/Assets.php
Resolved conflicts. Also add media-path, media-url
Replaces PR #336
=> Fix for absolute asset paths

htdocs/class/xoopseditor/tinymce4/external_plugins/filemanager/include/utils.php, htdocs/class/xoopseditor/tinymce4/formtinymce.php, htdocs/class/xoopseditor/tinymce4/readme.txt, htdocs/include/site-closed.php, htdocs/modules/banners/blocks/banners_blocks.php, htdocs/modules/page/docs/credits.txt, htdocs/modules/pm/docs/install.txt, htdocs/modules/pm/docs/readme.txt, htdocs/modules/profile/docs/install.txt, htdocs/modules/profile/docs/readme.txt, htdocs/modules/publisher/docs/install.txt, htdocs/modules/system/header.php, htdocs/modules/xlanguage/class/xlanguage.php, htdocs/modules/xlanguage/include/install.php, htdocs/uploads/filemanager/media/depot-members/config.php
Also, fix some encoding issues, and remove some unused code
=> Fixes for some scrutinizer reported issues

README.md
Quick link to waffle.io kanban board
=> Add badge for waffle.io WIP

htdocs/install/page_dbconnection.php
```
An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket 
```
Related to #289 and #321
=> Fixed Dude Exception Error Installation

htdocs/modules/system/templates/blocks/system_block_siteinfo.tpl
=> Fix Site Information block notice

.scrutinizer.yml, .travis.yml, htdocs/xoops_lib/Xoops/Core/Session/Handler.php
- Add PHP 7.0 and hhvm testing on travis-ci.org
- Fix one issue with session related message noted in (human) testing under PHP 7.0RC2
=> Adding PHP 7 testing

.travis.yml, htdocs/class/file/file.php, htdocs/class/file/folder.php, phpunit.xml, tests/unit/class/database/databasefactoryTest.php, tests/unit/class/file/fileTest.php, tests/unit/class/file/folderTest.php
- add phpunit.xml to project root
- simplify phpunit invocation in .travis-ci.yml
- fix or skip some platform dependent issues in file and folder
- correct test issue with anonymous database connection
=> Add class test suite to travis-ci

htdocs/modules/images/admin/images.php
Fix fault in image module, see #366
=> Remove obsolete define

htdocs/index.php
=> Remove remnant of an old transition

htdocs/modules/publisher/blocks/items_menu.php, htdocs/modules/publisher/category.php, htdocs/modules/publisher/templates/blocks/publisher_items_menu.tpl, htdocs/modules/publisher/templates/publisher_categories_table.tpl, htdocs/modules/publisher/templates/publisher_display_summary.tpl
Fix for #396 
Also, some cleanup some template errors.
=> Categories Menu Block in Publisher

htdocs/include/functions.php, htdocs/xoops_lib/Xmf/Module/Permission.php
Missed in the earlier handler refactoring
=> Legacy compatibility issue in xoops_getHandler()

htdocs/xoops_lib/Xoops/Core/Logger.php
Also, reduce to just message instead of full trace. See #372
=> Sanitize fatal exceptions

htdocs/modules/smilies/admin/smilies.php, htdocs/modules/smilies/class/SmiliesProvider.php, htdocs/modules/smilies/templates/admin/smilies_smilies.tpl, htdocs/modules/smilies/xoops_version.php, htdocs/xoops_lib/Xoops/Core/Service/Contract/EmojiInterface.php, htdocs/xoops_lib/Xoops/Form/DhtmlTextArea.php, tests/unit/xoopsLib/Xoops/Locale/AbstractTest.php
- small adjustment to EmojiInterface
- cleanup some smilies module issues
Also, tweak Locale/AbstractTest.php for random failures
=> Some Smilies/Emoji cleanup

htdocs/media/xoops/image.js, htdocs/xoops_lib/Xoops/Core/Text/Sanitizer/Extensions/Image.php, htdocs/xoops_lib/Xoops/Form/DhtmlTextArea.php
=> Re-add missing image.js

htdocs/modules/codex/form-tab.php, htdocs/modules/codex/form.php, tests/unit/xoopsLib/Xoops/Locale/AbstractTest.php
=> Fix ButtonTray calls in codex

htdocs/xoops_lib/Xoops/Core/Text/Sanitizer.php, htdocs/xoops_lib/Xoops/Core/Text/Sanitizer/Extensions/Flash.php, htdocs/xoops_lib/Xoops/Core/Text/Sanitizer/Extensions/Mp3.php, htdocs/xoops_lib/Xoops/Core/Text/Sanitizer/Extensions/SoundCloud.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/CensorTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/ClickableTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/FlashTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/IframeTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/ImageTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/MmsTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/Mp3Test.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/QuoteTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/RtspTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/SoundCloudTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/SyntaxHighlightTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/TextFilterTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/UnorderedListTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/WikiTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/WmpTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/XoopsCodeTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/XssTest.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/YouTubeTest.php
- Improve unit test coverage for sanitizer components.
- Update the Flash and Mp3 extensions to use standard shortcode syntax.
- Fix things found to be broken along the way.
=> Improve testing of sanitizer components

htdocs/modules/publisher/visit.php
It offered a very bogus fix suggestion, but it was in response to a real issue.
=> Fix issue flagged by scrutinizer

htdocs/class/database/mysqldatabase.php, htdocs/modules/maintenance/admin/center.php, htdocs/xoops_lib/Xoops/Core/Text/Sanitizer/Extensions/YouTube.php, htdocs/xoops_lib/Xoops/Form/Label.php, htdocs/xoops_lib/Xoops/Module/Admin.php, tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/YouTubeTest.php
Including:
- mirror changes in 2.5.8 for youtube embeds - thanks xd9527!
- some legacy db support issues
- add name to form label elements
=> Set of misc fixes

htdocs/class/xoopsload.php, htdocs/xoops_lib/Xoops/Core/Logger.php
- make XoopsLoad more resilient with include_once for module and framework classes
- add PHP version sensitive (5 vs 7) type check in exception handler
=> Two small fixes

htdocs/xoops_lib/Xoops/Core/Kernel/Dtype/DtypeMoney.php, tests/unit/xoopsLib/Xoops/Core/Kernel/Dtype/DtypeMoneyTest.php
The upcoming v3.0 of Money introduces the JsonSerializable interface on Money. These changes make sure our serialized data will be compatible with it when it is released.
=> Tweaking DtypeMoney

htdocs/modules/menus/templates/admin/menus_admin_menu.tpl, htdocs/modules/menus/templates/admin/menus_admin_menus.tpl, htdocs/modules/notifications/index.php, htdocs/modules/search/blocks/search_blocks.php, htdocs/modules/search/index.php, htdocs/modules/search/preloads/preload.php, htdocs/modules/system/blocks/user.php, htdocs/modules/system/templates/system_alert.tpl, htdocs/modules/system/xoops_version.php, htdocs/xoops_lib/Xoops.php, htdocs/xoops_lib/Xoops/Core/HttpRequest.php, htdocs/xoops_lib/Xoops/Core/Locale/Punic/Calendar.php, htdocs/xoops_lib/Xoops/Locale.php
- menus template errors
- search cleanup
- Administration link in User Menu no longer "external"
- typos and tweaks
=> Several small cleanups

htdocs/class/XoopsBaseConfig.php, htdocs/class/database/mysqldatabase.php, htdocs/class/xoopsform/grouppermform.php, htdocs/class/xoopsload.php, htdocs/class/xoopslocal.php, htdocs/include/common.php, htdocs/include/defines.php, htdocs/language/english/locale.php, htdocs/modules/system/class/module.php, htdocs/xoops_lib/Xoops/Core/Database/Factory.php, htdocs/xoops_lib/Xoops/Core/Kernel/XoopsObject.php, htdocs/xoops_lib/Xoops/Core/SmartyBCTrait.php, htdocs/xoops_lib/Xoops/Core/XoopsTpl.php, htdocs/xoops_lib/Xoops/Module/Admin.php
Correct some issues apparent when porting legacy modules.
=> Legacy support fixes

.travis.yml, htdocs/xoops_lib/Xoops/Core/Kernel/Dtype/DtypeMoney.php, htdocs/xoops_lib/Xoops/Core/Kernel/Model/Stats.php, tests/unit/xoopsLib/Xoops/Core/Kernel/Handlers/XoopsOnlineHandlerTest.php
Adapt to new package versions and new environments, correcting issues found in unit testing.
=> Test Fixes

htdocs/install/include/common.inc.php
Class include out of sequence. Fixes #508
=> Error in install

htdocs/modules/system/themes/default/default.php, htdocs/modules/system/themes/default/xotpl/icons.tpl
So I can only have one pull request per branch? Gotcha.
=> Admin : Show links to preferences only if module has preferences.

htdocs/xoops_lib/Xoops/Core/XoopsTpl.php, tests/unit/xoopsLib/Xoops/Core/XoopsTplTest.php
Not perfect, but smarter. Re #521
=> Improve Smarty Delimiter issue

htdocs/modules/system/templates/system_redirect.tpl, htdocs/xoops_lib/smarty/xoops_plugins/compiler.shortcode.php
Do you know why we are getting "not set" errors in 2.6.0?
=> Undefined index when using legacy logger

.travis.yml, htdocs/xoops_lib/Xoops/Core/Session/Handler.php, htdocs/xoops_lib/Xoops/Core/Session/Manager.php
=> Exception during session_regenerate_id

htdocs/modules/system/preloads/preload.php, htdocs/xoops_lib/Xoops/Core/Assets.php, htdocs/xoops_lib/Xoops/Core/Theme/XoopsTheme.php
Delete xoops_data/configs/system_assets_prefs.yml to rebuild with the new default settings and install for use.
=> Add fontawesome asset

htdocs/xoops_lib/Xoops/Form/Button.php, htdocs/xoops_lib/Xoops/Form/Hidden.php, htdocs/xoops_lib/Xoops/Form/Password.php
Value attributes rendered twice on Button, Hidden and Password (and children) elements.
=> Fixes to value attribute rendering

htdocs/modules/system/admin/groups/main.php, htdocs/modules/system/admin/users/main.php
Substitute constants for hardcoded group ids
=> Use FixedGroup constants

htdocs/class/tree.php
Changes in visibility address #540
=> Sync changes to XoopsObjectTree made in 2.5.9

htdocs/xoops_lib/Xmf/Metagen.php, tests/unit/xoopsLib/Xmf/MetagenTest.php
Addresses issue raised in https://github.com/XOOPS/xmf/issues/26
=> Use Unicode character properties, not ASCII ranges

.travis.yml, htdocs/xoops_lib/Xmf/Module/Helper/Permission.php
Re: XOOPS/xmf#29
Also, adding nightly build to travis-ci to test on PHP 7.2
=> Missing option to permission check

.travis.yml, htdocs/xoops_lib/Xmf/Debug.php, htdocs/xoops_lib/Xmf/Uuid.php, htdocs/xoops_lib/Xoops.php, htdocs/xoops_lib/Xoops/Core/HttpRequest.php, htdocs/xoops_lib/Xoops/Core/Logger.php, tests/unit/xoopsLib/Xmf/UuidTest.php, tests/unit/xoopsLib/XoopsTest.php
- fix ci build to include PHP 7.2, drop hhvm
- changes to kint
- remove php-domain-parser
- add regdom
- new Xmf component Uuid
=> Library updates

htdocs/xoops_lib/Xoops/Core/Cache/CacheManager.php
There appear to be several issues with the FileSystem driver, which we can try to avoid by defaulting to SQLite:
- Windows path length (see #560)
- Occasional errors reported under load (race?)
=> Use SQLite driver for Stash if available

phpunit.xml.dist, tests/unit/xoopsLib/Xoops/Core/Exception/NotSupportedExceptionTest.php, xoops_lib/Xoops/Core/Exception/NotSupportedException.php
- fix incorrect paths in phpunit.xml.dist
- Add a simple missing test while testing fixes
=> Fix coverage errors

.travis.yml, htdocs/include/defines.php, htdocs/modules/codex/usermessage.php, htdocs/modules/debugbar/class/debugbarlogger.php, htdocs/modules/pm/class/PMProvider.php, htdocs/modules/pm/preloads/preload.php, phpcs.xml.dist, tests/unit/xoopsLib/Xoops/Core/Service/Data/MessageTest.php, tests/unit/xoopsLib/Xoops/Core/Theme/NullThemeTest.php, xoops_lib/Xoops/Core/Handler/bootstrap.php, xoops_lib/Xoops/Core/Service/Contract/UserMessageInterface.php, xoops_lib/Xoops/Core/Service/Data/Message.php, xoops_lib/Xoops/Core/Service/Provider.php, xoops_lib/Xoops/Core/Theme/NullTheme.php
- usage: to send message from one user to another user
- adds Message data object
- adds provider via pm module (via email will follow)
- adds example in codex
=> Adding UserMessage service

tests/unit/xoopsLib/Xmf/Jwt/JsonWebTokenTest.php, tests/unit/xoopsLib/Xmf/Jwt/KeyFactoryTest.php, tests/unit/xoopsLib/Xmf/Jwt/TokenFactoryTest.php, tests/unit/xoopsLib/Xmf/Jwt/TokenReaderTest.php, tests/unit/xoopsLib/Xmf/Key/BasicTest.php, tests/unit/xoopsLib/Xmf/Key/FileStorageTest.php, tests/unit/xoopsLib/Xmf/Key/KeyAbstractTest.php, tests/unit/xoopsLib/Xmf/Key/StorageInterfaceTest.php, xoops_lib/Xmf/Jwt/KeyFactory.php, xoops_lib/Xmf/Jwt/TokenFactory.php, xoops_lib/Xmf/Jwt/TokenReader.php, xoops_lib/Xmf/Key/FileStorage.php, xoops_lib/Xmf/Module/Helper/AbstractHelper.php, xoops_lib/Xmf/Module/Helper/Cache.php
=> Match changes in XOOPS\xmf

tests/unit/xoopsLib/Xoops/Locale/MessageFormatterTest.php, xoops_lib/Xoops/Locale/MessageFormatter.php
Sync with upstream fixes, add tests
=> MessageFormatter updates

htdocs/themes/default/theme_onload.php, xoops_lib/Xoops/Core/Theme/XoopsTheme.php, xoops_lib/Xoops/Form/Button.php, xoops_lib/Xoops/Form/ButtonTray.php, xoops_lib/Xoops/Form/Captcha.php, xoops_lib/Xoops/Form/Checkbox.php, xoops_lib/Xoops/Form/ColorPicker.php, xoops_lib/Xoops/Form/DateSelect.php, xoops_lib/Xoops/Form/DhtmlTextArea.php, xoops_lib/Xoops/Form/Editor.php, xoops_lib/Xoops/Form/Element.php, xoops_lib/Xoops/Form/ElementTray.php, xoops_lib/Xoops/Form/File.php, xoops_lib/Xoops/Form/GroupFormCheckbox.php, xoops_lib/Xoops/Form/Hidden.php, xoops_lib/Xoops/Form/Label.php, xoops_lib/Xoops/Form/Password.php, xoops_lib/Xoops/Form/Radio.php, xoops_lib/Xoops/Form/Raw.php, xoops_lib/Xoops/Form/Renderer/Bootstrap3Renderer.php, xoops_lib/Xoops/Form/RendererInterface.php, xoops_lib/Xoops/Form/Select.php, xoops_lib/Xoops/Form/SelectEditor.php, xoops_lib/Xoops/Form/Tab.php, xoops_lib/Xoops/Form/TabTray.php, xoops_lib/Xoops/Form/Text.php, xoops_lib/Xoops/Form/TextArea.php, xoops_lib/Xoops/Html/Attributes.php
=> Formrender

tests/unit/class/xoopsform/formTest.php, tests/unit/class/xoopsform/formelementTest.php, tests/unit/xoopsLib/Xoops/Form/ButtonTest.php, tests/unit/xoopsLib/Xoops/Form/ElementTest.php, tests/unit/xoopsLib/Xoops/Form/TabTest.php, xoops_lib/Xoops/Form/SelectEditor.php
=> Fix test breaks related to form changes

xoops_lib/Xoops/Core/Service/Manager.php
- path() was being applied twice
- code standards cleanup
=> Fix provider preference read

htdocs/modules/codex/locale.php, htdocs/modules/codex/locale/de/de.php, htdocs/modules/codex/locale/de/index.html, htdocs/modules/codex/locale/de/locale.php, htdocs/modules/codex/locale/pl/index.html, htdocs/modules/codex/locale/pl/locale.php, htdocs/modules/codex/locale/pl/pl.php
Added translations to test the Punic CLDR library
=> feat(codex): German and Polish translation

console/Commands/ActivateModuleCommand.php, console/Commands/DeactivateModuleCommand.php, console/console.php, htdocs/modules/monolog/preloads/preload.php, xoops_lib/Xoops/Core/Kernel/Handlers/XoopsModuleHandler.php
- add activate-module command
- add deactivate-module command
- minor tweak to monolog for minimal startup operation
example: `php console.php deactivate-module modulename`
=> Console command additions

xoops_lib/Xoops/Core/Logger.php
Process silenced deprecation messages, i.e.:
```php
@trigger_error('message', E_USER_DEPRECATED);
```
=> Handle Symfony style deprecation

xoops_lib/Xoops/Core/Kernel/Handlers/XoopsModule.php, xoops_lib/Xoops/Core/Kernel/Handlers/XoopsModuleHandler.php
Case issue in setting some variables.
=> Fix regression in XoopsModule::loadInfoAsVar()

htdocs/modules/schematool/admin/schematool.php, htdocs/modules/system/class/module.php, tests/unit/xoopsLib/Xoops/Core/Database/Schema/ExportVisitorTest.php, tests/unit/xoopsLib/Xoops/Core/Database/Schema/ImportSchemaTest.php, tests/unit/xoopsLib/Xoops/Core/Database/Schema/PrefixStripperTest.php, tests/unit/xoopsLib/Xoops/Core/Database/Schema/RemovePrefixesTest.php, xoops_lib/Xoops/Core/Database/Schema/ExportVisitor.php, xoops_lib/Xoops/Core/Database/Schema/ImportSchema.php, xoops_lib/Xoops/Core/Database/Schema/PrefixStripper.php, xoops_lib/Xoops/Core/Database/Schema/RemovePrefixes.php
- cleanup deprecated/future removal notices from Doctrine
- move prefix and table filter list to relevant constructors.
- Update schematool module,  SystemModule class and tests accordingly.
=> Update schema generation

xoops_lib/Xoops/Form/Select.php
=> FormSelect 'selected' syntax

htdocs/modules/comments/admin/header.php, htdocs/modules/comments/admin/main.php, htdocs/modules/comments/class/helper.php, htdocs/modules/comments/xoops_version.php
- add confirm to comment purge
- fix issue with module comment rules not being honored
- switch System::cleanVars() to Xmf/Request
=> Some fixes in comments module

htdocs/modules/page/admin/header.php, htdocs/modules/page/admin/permissions.php, htdocs/modules/page/blocks/page_blocks.php, htdocs/modules/page/class/form/page_content.php, htdocs/modules/page/class/form/page_related.php, htdocs/modules/page/header.php, htdocs/modules/page/pdf.php, htdocs/modules/page/print.php
- switch System::cleanVars() to Xmf/Request
- string array conversion error in blocks
- invoke Sanitizer::displayTarea() on content for pdf and print
- replace setExtra() in form elements
=> Some fixes in page module

htdocs/include/cp_header.php, htdocs/modules/images/admin/header.php, htdocs/modules/profile/admin/category.php, htdocs/modules/profile/admin/field.php, htdocs/modules/profile/admin/permissions.php, htdocs/modules/profile/admin/step.php, htdocs/modules/profile/admin/visibility.php, htdocs/modules/system/admin.php, htdocs/modules/system/admin/blocksadmin/main.php, htdocs/modules/system/admin/extensions/main.php, htdocs/modules/system/admin/groups/main.php, htdocs/modules/system/admin/modulesadmin/main.php, htdocs/modules/system/admin/preferences/main.php, htdocs/modules/system/admin/tplsets/main.php, htdocs/modules/system/admin/users/jquery.php, htdocs/modules/system/admin/users/main.php, htdocs/modules/system/blocks/main.php, htdocs/modules/system/class/system.php, htdocs/modules/system/header.php, htdocs/modules/system/help.php, htdocs/modules/userrank/admin/userrank.php
Continue removing System::cleanVars()
=> Standardize with Request

tests/unit/xoopsLib/Xoops/Core/Text/Sanitizer/Extensions/EmbedTest.php, xoops_lib/smarty/xoops_plugins/function.xoInboxCount.php
- add total parameter
- use Smarty 3 signatures
- code standard cleanup
=> Match 2.5.10 functionality

.travis.yml, htdocs/modules/system/admin/users/main.php
=> Typo in system module, admin user sync
